### ISSUE TITLE
Call Symfony class with Lambda event 

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [brefphp/bref#562] opened 2020-02-18 13:24 UTC
Hi all, I would like to know how can I call a method inside a class when a created event invokes the handler.
This is my serverless.yml file:

```
service: symfony-bref

provider:
    name: aws
    region: eu-central-1
    runtime: provided
    environment:
        APP_ENV: prod

plugins:
    - ./vendor/bref/bref

functions:
    api:
        handler: public/index.php
        description: ''
        timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
        layers:
            - ${bref:layer.php-73-fpm}
        events:
            -   http: 'ANY /'
            -   http: 'ANY /{proxy+}'

    S3Handler:
        handler: public/s3-handler.php
        layers:
            - ${bref:layer.php-73}
        events:
            - s3:
                bucket: ${ssm:/symfony-bref/AWS_S3_BUCKET_NAME:1}
                event: s3:ObjectCreated:*
                existing: true

```

This is my s3-handler.php file inside folder public

```
<?php

use App\UseCase\RenamePhoto;
use App\Kernel;
use Symfony\Component\HttpFoundation\Request;

require dirname(__DIR__).'/config/bootstrap.php';
$kernel = new Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);
$kernel->boot();

$request = Request::createFromGlobals();

return $kernel->getContainer()->get(RenamePhoto::class);
```

My class RenamePhoto is something like that:

```
<?php

namespace App\UseCase;

use Bref\Context\Context;
use Bref\Event\S3\S3Event;
use Bref\Event\S3\S3Handler;
use Psr\Log\LoggerInterface;

class RenamePhoto extends S3Handler
{
    /**
     * @var LoggerInterface
     */
    private $logger;

    public function __construct(LoggerInterface $logger)
    {
        $this->logger = $logger;
        $this->logger->error('Invoked');
    }

    public function handleS3(S3Event $event, Context $context): void
    {
        $filename = $event->getRecords()[0]->getObject()->getKey();
        $this->logger->info('A new file was uploaded', [
            'filename' => $filename,
        ]);

    }
}
```

I have tried to invoke the file in many ways like:

handler: public/s3-handler.handle
handler: public/s3-handler.handleS3
handler: public/s3-handler.php.handle
handler: public/s3-handler.php.handleS3

Returns me always that it doesn't exist like this:

Handler `/var/task/public/s3-handler.handle` doesn't exist

How can I invoke my class from an event?
Thanks

**Comment by Kocal** [comment] 2020-02-18 14:07
I don't know if it's possible, but what about using `__invoke` function?

**Comment by AlessandroMinoccheri** [comment] 2020-02-18 14:09
I don't know if is correct to use invoke because I need the event as an argument.

**Comment by mnapoli** [comment] 2020-02-21 12:04
`handler: public/s3-handler.php` looks perfectly correct. All other options you mentioned are invalid indeed.

What was the error that you got?

**Comment by AlessandroMinoccheri** [comment] 2020-02-21 17:03
I can't see any events triggered.

**Comment by mnapoli** [comment] 2020-02-24 11:12
Well then the problem is elsewhere, it's not with the code. Your code is not triggered at all.

Your configuration might be off, or your file upload script. Closing as this isn't related to a Bref bug.

**Closed by mnapoli** 2020-02-24 11:12 UTC
Labels: support
