### ISSUE TITLE
Incorrect symfony/process requirement

### ISSUE THREAD

**Issue by amacrobert-meq** [brefphp/bref#1146] opened 2022-01-28 16:02 UTC
Hi, I'm not sure if we care about this particular problem (I ran into it while working on a legacy Symfony 3.4 microservice). But I think it shows that tests should be run both with `--prefer-lowest` and `--prefer-stable` to make sure this class of problems doesn't go unchecked in the future.

**Description:**

Bref 1.2.4 is the first version of Bref that uses `Symfony\Component\Process\Process::fromShellCommandline()` (in `runtime/layers/console/bootstrap`).

`fromShellCommandline` was added to symfony/process 4.2. Therefore, Bref 1.2.4 should have a minimum requirement of symfony/process 4.2. It actuality, its version constraint is:
```
"symfony/process": "^3.3|^4.0|^5.0"
```

This causes console commands to fail when run on Lambda if using an earlier Symfony version:

**How to reproduce:**

Create a Symfony application <4.2. Use Bref >=1.2.4.
Create a function that uses bin/console as the handler.
Run it on Lambda and you'll get this error:
```
{
  "errorType": "Error",
  "errorMessage": "Call to undefined method Symfony\\Component\\Process\\Process::fromShellCommandline()",
  "stackTrace": [
    "#0 /var/task/vendor/bref/bref/src/Runtime/Invoker.php(34): {closure}('doctrine:migrat...', Object(Bref\\Context\\Context))",
    "#1 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(102): Bref\\Runtime\\Invoker->invoke(Object(Closure), 'doctrine:migrat...', Object(Bref\\Context\\Context))",
    "#2 /opt/bootstrap(65): Bref\\Runtime\\LambdaRuntime->processNextEvent(Object(Closure))",
    "#3 {main}"
  ]
}
```

**Comment by GrahamCampbell** [comment] 2022-02-18 09:29
Not a bug, fixed on the latest version.

**Comment by GrahamCampbell** [comment] 2022-02-18 09:29
Bref cannot be used with symonfy/process 3.

**Closed** 2022-02-18 12:02 UTC
Labels: bug
