### ISSUE TITLE
Unable to use variables from external file reference

### ISSUE THREAD

**Issue by Blacksmoke16** [brefphp/bref#888] opened 2021-03-18 18:41 UTC
**Description:**

This is similar to https://github.com/brefphp/bref/issues/372, but related to the ability to reference an [external file](https://www.serverless.com/framework/docs/providers/aws/guide/variables#reference-variables-in-other-files) as an object.  I'm pretty sure this is a `bref` issue as our serverless version hasn't changed and this error did not reproduce when using `bref` `0.5.10`. 

**How to reproduce:**

Do something like:

`serverless-variables.yml`
```yaml
region: us-east-1
```

`serverless.yml`
```yaml
variables: ${file(./serverless-variables.yml)}

provider:
  name: aws
  runtime: provided.al2
  region: ${self:variables.region}

plugins:
  - ./vendor/bref/bref

functions:
  console:
    handler: app/console
    layers:
      - ${bref:layer.php-74}
      - ${bref:layer.console}
```

Then when running `sls info` for example:

```sh
 Serverless Warning --------------------------------------

  A valid service attribute to satisfy the declaration 'self:variables.region' could not be found.


 Exception -----------------------------------------------

  'There is no Bref layer named "php-74" in region "[object Object]"'

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.16.3
     Framework Version:         1.55.1
     Plugin Version:            3.2.0
     SDK Version:               2.1.2
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

It seems the `.region` is not being resolved to the underlying value correctly.  Accessing a specific property in the file works as expected, e.g. `region: ${file(./serverless-variables.yml):region}`.

**Comment by mnapoli** [comment] 2021-03-18 20:02
Yes indeed, it may be because the Bref plugin (for serverless.yml) is acting too early, or is not recursively resolving variable region names.

This is possibly a bug in https://github.com/brefphp/bref/blob/master/index.js

**Comment by deleugpn** [comment] 2021-05-24 10:46
hey @Blacksmoke16 I was trying to reproduce this issue and it seems like it may be already fixed on the most recent version? 
Could you check to see if you can still reproduce this?

Thanks!

**Comment by Blacksmoke16** [comment] 2021-05-24 14:09
@deleugpn I upgraded to `1.2.6` from `1.2.0` and ran thru the same steps:

```sh
sls info

 Serverless Warning --------------------------------------

  A valid service attribute to satisfy the declaration 'self:variables.region' could not be found.


 Exception -----------------------------------------------

  'There is no Bref layer named "php-74" in region "[object Object]"'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.16.3
     Framework Version:         1.55.1
     Plugin Version:            3.2.0
     SDK Version:               2.1.2
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
```

It seems the issue persists.

**Comment by deleugpn** [comment] 2021-05-24 14:58
Perhaps it could be your `Serverless` version? I see you're using `1.55.1` while I have `2.43.0`

**Comment by Blacksmoke16** [comment] 2021-05-24 15:19
@deleugpn So I did some additional testing based on different Serverless versions.

When upgrading to `2.43.0`, it works but shows a deprecation warning of `Configuration warning at root: unrecognized property 'variables'`.  Changing the property name to `custom` (like in their docs) fixes that.

Dropping back down to the latest `1.x` version, with the `variables` name reproduces the issue.  Changing that to `custom` results in `TypeError: Cannot create property 'bref' on string '${file(./serverless-variables.yml)}'`.

What's interesting is that this used to work with Serverless using Bref `0.5.10`.  However given everything seems to be fine on the latest version of Serverless and Bref there is probably nothing actionable, so feel free to close.

**Comment by deleugpn** [comment] 2021-05-24 15:37
Glad to know it's working!

**Closed by deleugpn** 2021-05-24 15:37 UTC
Labels: help wanted
