### ISSUE TITLE
Failed to fetch next Lambda invocation

### ISSUE THREAD

**Issue by matthewsuan** [brefphp/bref#1562] opened 2023-06-09 16:58 UTC
**Description:**
I got the error below using bref:layer.php-81.
```
[2023-06-09 16:26:37] production.ERROR: Failed to fetch next Lambda invocation: The requested URL returned error: 403 {"exception":"[object] (Exception(code: 0): Failed to fetch next Lambda invocation: The requested URL returned error: 403 at /tmp/vendor/bref/bref/src/Runtime/LambdaRuntime.php:158)
```

This is happening intermittently and reproduction is an issue. 

Are there any reasons why `/runtime/invocation/next` would cause 403?

Bref version: 1.7.25

**Comment by mnapoli** [comment] 2023-06-09 17:56
No obvious reason, that's interesting. We did change a few things in Bref v2 (e.g. when dealing with payloads too big), so honestly it might be worth trying Bref v2.

**Comment by matthewsuan** [comment] 2023-06-10 05:24
Thanks @mnapoli, as always. I'll try v2 and also contact AWS support for whatever reason 403 are thrown when fetching next invocations.

**Comment by sladg** [comment] 2023-06-14 07:58
👋 connected with #1368. I have seen similar message on version 1. Upgrade to version 2 gave us a slightly different error
```

{
    "errorType": "Exception",
    "errorMessage": "Error 403 while calling the Lambda runtime API: InvalidStateTransition: State transition from RuntimeResponseSentState to InvocationResponse failed for runtime. Error: State transition is not allowed",
    "stack": [
        "#0 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(181): Bref\\Runtime\\LambdaRuntime->postJson('http://127.0.0....', Array)",
        "#1 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(91): Bref\\Runtime\\LambdaRuntime->sendResponse('ff1036c8-1971-4...', Array)",
        "#2 /var/task/vendor/bref/bref/src/FpmRuntime/Main.php(42): Bref\\Runtime\\LambdaRuntime->processNextEvent(Object(Bref\\FpmRuntime\\FpmHandler))",
        "#3 /opt/bref/bootstrap.php(17): Bref\\FpmRuntime\\Main::run()",
        "#4 {main}"
    ]
}
```

It's happening virtually for every request, however, there is no apparent impact, Lambda returns data and processes request normally. We gave up on debugging as we couldn't figure out the cause.

**Comment by lanlin** [comment] 2023-08-03 06:53
**same error on `bref/php-82-fpm-dev:latest` : Failed to fetch next Lambda invocation**

```shell
dev1  | START RequestId: 42b8c88d-59d9-47c1-90db-e7221f158ac8 Version: $LATEST
dev1  | 03 Aug 2023 06:45:04,406 [INFO] (rapid) extensionsDisabledByLayer(/opt/disable-extensions-jwigqn8j) -> stat /opt/disable-extensions-jwigqn8j: no such file or directory
dev1  | 03 Aug 2023 06:45:04,408 [INFO] (rapid) Configuring and starting Operator Domain
dev1  | 03 Aug 2023 06:45:04,408 [INFO] (rapid) Starting runtime domain
dev1  | 03 Aug 2023 06:45:04,409 [WARNING] (rapid) Cannot list external agents error=open /opt/extensions: no such file or directory
dev1  | [03-Aug-2023 06:45:05] NOTICE: fpm is running, pid 32
dev1  | [03-Aug-2023 06:45:05] NOTICE: ready to handle connections
dev1  | 1691045105
dev1  |
dev1  | Fatal error: Uncaught Exception: Failed to fetch next Lambda invocation: The requested URL returned error: 502 in /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php:159
dev1  | Stack trace:
dev1  | #0 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(82): Bref\Runtime\LambdaRuntime->waitNextInvocation()
dev1  | #1 /var/task/vendor/bref/bref/src/FpmRuntime/Main.php(43): Bref\Runtime\LambdaRuntime->processNextEvent(Object(Bref\FpmRuntime\FpmHandler))
dev1  | #2 /opt/bref/bootstrap.php(17): Bref\FpmRuntime\Main::run()
dev1  | #3 {main}
dev1  |   thrown in /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php on line 159
```

**Comment by lanlin** [comment] 2023-08-04 01:37
@mnapoli running locally. I just upgrade the image to the latest version. this error occur in every first request, and then all others request will not be delivered

```shell
dev1  | ⚡️ Server is running at http://localhost:8000
dev1  | 04 Aug 2023 01:32:41,688 [INFO] (rapid) extensionsDisabledByLayer(/opt/disable-extensions-jwigqn8j) -> stat /opt/disable-extensions-jwigqn8j: no such file or directory
dev1  | START RequestId: 6a5402e4-5343-41ba-acfc-5dc9a5379e09 Version: $LATEST
dev1  | 04 Aug 2023 01:32:41,688 [INFO] (rapid) Configuring and starting Operator Domain
dev1  | 04 Aug 2023 01:32:41,688 [INFO] (rapid) Starting runtime domain
dev1  | 04 Aug 2023 01:32:41,689 [WARNING] (rapid) Cannot list external agents error=open /opt/extensions: no such file or directory
dev1  | [04-Aug-2023 01:32:43] NOTICE: fpm is running, pid 31
dev1  | [04-Aug-2023 01:32:43] NOTICE: ready to handle connections
dev1  | 1691112763
dev1  |
dev1  | Fatal error: Uncaught Exception: Failed to fetch next Lambda invocation: The requested URL returned error: 502 in /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php:159
dev1  | Stack trace:
dev1  | #0 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(82): Bref\Runtime\LambdaRuntime->waitNextInvocation()
dev1  | #1 /var/task/vendor/bref/bref/src/FpmRuntime/Main.php(43): Bref\Runtime\LambdaRuntime->processNextEvent(Object(Bref\FpmRuntime\FpmHandler))
dev1  | #2 /opt/bref/bootstrap.php(17): Bref\FpmRuntime\Main::run()
dev1  | #3 {main}
dev1  |   thrown in /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php on line 159
dev1  |
dev1  | [04-Aug-2023 01:32:43] NOTICE: Terminating ...
dev1  | [04-Aug-2023 01:32:43] NOTICE: exiting, bye-bye!
dev1  | 04 Aug 2023 01:32:43,287 [WARNING] (rapid) First fatal error stored in appctx: Runtime.ExitError
dev1  | 04 Aug 2023 01:32:43,288 [WARNING] (rapid) Process runtime-1 exited: exit status 255
dev1  | 04 Aug 2023 01:32:43,288 [ERROR] (rapid) Init failed error=Runtime exited with error: exit status 255 InvokeID=
dev1  | 04 Aug 2023 01:32:43,289 [INFO] (rapid) Starting runtime domain
dev1  | 04 Aug 2023 01:32:43,289 [WARNING] (rapid) Cannot list external agents error=open /opt/extensions: no such file or directory
dev1  | END RequestId: 5fc7412e-ed3a-4997-8988-8fc0e9ae358b
dev1  | REPORT RequestId: 5fc7412e-ed3a-4997-8988-8fc0e9ae358b	Init Duration: 0.32 ms	Duration: 1601.77 ms	Billed Duration: 1602 ms	Memory Size: 3008 MB	Max Memory Used: 3008 MB
dev1  | START RequestId: 69c46468-f675-4d74-a683-348cb2053d2a Version: $LATEST
dev1  | 04 Aug 2023 01:32:43,716 [INFO] (rapid) Starting runtime domain
dev1  | 04 Aug 2023 01:32:43,716 [WARNING] (rapid) Cannot list external agents error=open /opt/extensions: no such file or directory
dev1  | END RequestId: 48261bc0-1750-4f22-b3a1-8153872c2349
dev1  | REPORT RequestId: 48261bc0-1750-4f22-b3a1-8153872c2349	Duration: 0.87 ms	Billed Duration: 1 ms	Memory Size: 3008 MB	Max Memory Used: 3008 MB
dev1  | 04 Aug 2023 01:32:49,593 [INFO] (rapid) Starting runtime domain
dev1  | 04 Aug 2023 01:32:49,593 [WARNING] (rapid) Cannot list external agents error=open /opt/extensions: no such file or directory
dev1  | START RequestId: 7e2dea12-f71b-4c4d-b02f-a94389544980 Version: $LATEST
dev1  | END RequestId: ffe68485-223c-4ae4-b3a7-7d7b50b6fee5
dev1  | REPORT RequestId: ffe68485-223c-4ae4-b3a7-7d7b50b6fee5	Duration: 0.18 ms	Billed Duration: 1 ms	Memory Size: 3008 MB	Max Memory Used: 3008 MB
dev1  | START RequestId: 65bb40bc-9487-444a-a7d2-ae03527e4c81 Version: $LATEST
dev1  | END RequestId: fe1f88c0-3261-4f96-acec-c195d56fc7c9
dev1  | REPORT RequestId: fe1f88c0-3261-4f96-acec-c195d56fc7c9	Duration: 0.22 ms	Billed Duration: 1 ms	Memory Size: 3008 MB	Max Memory Used: 3008 MB
dev1  | 04 Aug 2023 01:32:49,734 [INFO] (rapid) Starting runtime domain
dev1  | 04 Aug 2023 01:32:49,734 [WARNING] (rapid) Cannot list external agents error=open /opt/extensions: no such file or directory
dev1  | START RequestId: 82dc646c-a45f-4e17-b0a0-676482f8ae9e Version: $LATEST
dev1  | 04 Aug 2023 01:32:52,624 [INFO] (rapid) Starting runtime domain
dev1  | 04 Aug 2023 01:32:52,625 [WARNING] (rapid) Cannot list external agents error=open /opt/extensions: no such file or directory
dev1  | END RequestId: b38ad622-c92c-40e5-aeac-2a9a566aaea8
dev1  | REPORT RequestId: b38ad622-c92c-40e5-aeac-2a9a566aaea8	Duration: 2.03 ms	Billed Duration: 3 ms	Memory Size: 3008 MB	Max Memory Used: 3008 MB
dev1  | START RequestId: 1dab2983-2605-44d4-8b4b-6ef8b54902d7 Version: $LATEST
dev1  | 04 Aug 2023 01:32:52,780 [INFO] (rapid) Starting runtime domain
dev1  | 04 Aug 2023 01:32:52,780 [WARNING] (rapid) Cannot list external agents error=open /opt/extensions: no such file or directory
dev1  | END RequestId: 2242be36-2e67-4d5e-86ac-3e37748443de
dev1  | REPORT RequestId: 2242be36-2e67-4d5e-86ac-3e37748443de	Duration: 0.52 ms	Billed Duration: 1 ms	Memory Size: 3008 MB	Max Memory Used: 3008 MB
```

**Comment by harshal-ringe** [comment] 2024-02-01 07:53
Hi @mnapoli,

I'm also facing the same issue randomly for the bref/php-73 docker image.
The bref version's are
`"bref/bref": "^1.7"`
`"bref/laravel-bridge": "^1.2"`

I get below error at `vendor/bref/bref/src/Runtime/LambdaRuntime.php:158` from `waitNextInvocation` function.
_Failed to fetch next Lambda invocation: The requested URL returned error: 403_

Check this [sentry error log](https://247software.sentry.io/share/issue/079b0a22e12e414f84d0db3fa23f6c80/)


We are using multiple SQS FIFO to trigger the AWS Lambda. The batch size for each queue is different and the max batch size is 10. Whenever SQS triggers the lambda, it also sends the SQS message in the request body.

Could you please explain why bref runtime calling Lambda API if it already getting all payload in the request?
Is there any workaround to solve this issue?

**Comment by mnapoli** [comment] 2024-02-01 15:24
@harshal-ringe this is unfortunately Bref v1 with an obsolete PHP version, so many things have changed since then. I encourage you to either upgrade, or investigate, but chances are that upgrading might solve this.

Since this issue contains report either about v1, or about local development, I'll be closing it.

If this happens with v2 please open a new issue with as much detail as possible so that we can investigate! Thanks!

**Closed by mnapoli** 2024-02-01 15:24 UTC
Labels: bug
