### ISSUE TITLE
Update path for with-config-file-scan-dir

### ISSUE THREAD

**Issue by Nyholm** [brefphp/bref#355] opened 2019-06-21 12:21 UTC
We currently write: 
```   
--with-config-file-scan-dir=${INSTALL_DIR}/etc/php/conf.d:/var/task/php/conf.d 
```

This creates a folder in my docker image as `/opt/bref/etc/php/conf.d:/var/task/php/conf.d`. That is clearly not what we want. I **think** the correct solution is to write: 

```   
--with-config-file-scan-dir=${INSTALL_DIR}/etc/php/conf.d
--with-config-file-scan-dir=/var/task/php/conf.d 
```

But Im not sure how I would verify that.

**Comment by mnapoli** [comment] 2019-06-23 18:09
To be clear:

> This creates a folder in my docker image

Can you confirm that there is no problem at runtime, and that the problem is that there is a broken directory created in the docker image?

I'm not against changing the line so that the directory isn't created. But I don't know if the alternative works as expected. Is the random directory a problem? Since it's just in the Docker image is there any negative impact?

**Comment by Nyholm** [comment] 2019-06-23 20:17
> Can you confirm that there is no problem at runtime, and that the problem is that there is a broken directory created in the docker image?

Correct. 

>  Is the random directory a problem? Since it's just in the Docker image is there any negative impact?

I now think one can only have one directory as `with-config-file-scan-dir`. (I've done some testing).

Since the current implementation is broken, nobody relies on this feature. We also have no files created in `/opt/bref/etc/php/conf.d`. I suggest we change it to `/var/task/php/conf.d`. 

That means that I, as a user, can put ini files in `my-project/php/conf.d`.

**Comment by deleugpn** [comment] 2019-06-23 22:30
I dont understand the issue. I already have ini files in `./php/conf.d/` and it works fine.

**Comment by Nyholm** [comment] 2019-06-24 12:20
Hm, are you sure @deleugpn? And you have not specified a `PHP_INI_SCAN_DIR` parameter?

**Comment by deleugpn** [comment] 2019-06-24 12:57
Where would I have PHP_INI_SCAN_DIR? Anybody using pdo_mysql or redis on Lambda is probably forced to have a ini file with the following content:

```
extension=pdo_mysql
extension=redis
```

The lambda doesn't work without it otherwise

**Comment by Nyholm** [comment] 2019-06-24 13:05
You can define your sam template like: 

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
    Function:
        Environment:
            Variables:
                APP_ENV: prod
                APP_SECRET: 'foobar'
                PHP_INI_SCAN_DIR: /var/task/custom-php-folder-in-project-dir
               
Resources:
    Website:
        Type: AWS::Serverless::Function
        Code: ..
        Properties:
            FunctionName: 'my app'
       # ...
```

Then you can add your `php.ini` file in `/Users/tobias/project-dir/custom-php-folder-in-project-dir`. 

Do you mean that you never defined `PHP_INI_SCAN_DIR` and you are using whatever default value?

**Comment by deleugpn** [comment] 2019-06-24 13:12
Yes, I never defined any `PHP_INI_SCAN_DIR` variable. I just placed the `php.ini` inside `./php/conf.d/` with the contents mentioned above.

**Comment by Nyholm** [comment] 2019-06-24 13:37
Im surprised that work to be honest. =)

Im not suggesting to change that. 

What we currently support is to load *.ini files in `/opt/bref/etc/php/conf.d` (inside the runtime). 
That does not work at the moment because it will create a weird folder at `/opt/bref/etc/php/conf.d:/var/task/php/conf.d`. 

Im suggesting to remove the thing that does not work. You should be able to continue to use `./php/conf.d/`.

**Comment by mnapoli** [comment] 2019-06-26 15:08
I'm continuing the discussion here (instead of #359) to keep the context.

Are we sure that `/opt/bref/etc/php/conf.d` doesn't work? I mean I realize that the directory that is created is incorrect, but this could be a bug limited to the directory creation. If `/opt/bref/etc/php/conf.d/*.ini` files are actually loaded then we may want to keep this behavior.

The goal of this behavior is that people can create Lambda layers for PHP extensions. In those layers you can add the `.so` extension file _and_ the `.ini` file that will load and configure the extension automatically. That way users just have to include the layer and that's it.

If we merge #359 then this feature is broken. But maybe it is already broken.

**Comment by nealio82** [comment] 2019-06-28 12:01
If I've read this correctly, then it seems that merging #359 means that _all_ modifications to `php.ini` must be made in `proj-root/php/conf.d`, and that adding PHP extensions via layers can't be automatically enabled / configured by including their own `php.ini` along with the `.so`?

Personally I don't think it'd be too much of a problem with that behaviour. It'd then mean it's a case of including the layer and then having to do some config work in a standardised place (`/proj-root/php/conf.d/php.ini`) rather than having magic in 3rd-party layers potentially messing with your own custom settings.

In essence, I don't see any difference between that and configuring 3rd-party Symfony bundles (for example)

**Comment by mnapoli** [comment] 2019-07-28 08:37
TBH I'd rather keep the current behavior where adding an extension is a matter of simply including the layer.

Unless there is a bug with that behavior let's revisit this but in the meantime I'll close this issue.

**Closed by mnapoli** 2019-07-28 08:37 UTC
Labels: bug
