### ISSUE TITLE
/tmp is not writable after recent bref/php-73-fpm-dev changes

### ISSUE THREAD

**Issue by dhrrgn** [brefphp/bref#464] opened 2019-09-20 17:30 UTC
After the recent updates to the bref/php-73-fpm-dev image, `/tmp` is no longer writable by all.  The permissions are as follows:

```bash
bash-4.2$ ls -al /tmp
total 12
drwx------ 1 sbx_user1051  495 4096 Sep 20 16:38 .
drwxr-xr-x 1 root         root 4096 Sep 20 16:38 ..
-rw-r--r-- 1 sbx_user1051  495    1 Sep 20 16:38 php-fpm.pid
```

Previously, root owned the directory and it was globally writable.

## Workaround

We worked around this by add a volume to our container mounted at `/tmp`:

```yml
  php:
    container_name: php
    image: bref/php-73-fpm-dev
    restart: always
    volumes:
      - .:/var/task:cached
      - ./var/cache:/tmp
```

**Comment by mnapoli** [comment] 2019-09-20 17:36
Thank you for the report. I cannot reproduce however, here is what I tried:

```bash
❯ docker run --rm -it bref/php-73-fpm-dev bash

bash-4.2$ ls -la /tmp
total 8
drwx------ 2 sbx_user1051  495 4096 Aug 16 17:31 .
drwxr-xr-x 1 root         root 4096 Sep 20 17:34 ..

bash-4.2$ whoami
sbx_user1051

bash-4.2$ touch /tmp/test

bash-4.2$ ls -la /tmp
total 8
drwx------ 1 sbx_user1051  495 4096 Sep 20 17:35 .
drwxr-xr-x 1 root         root 4096 Sep 20 17:34 ..
-rw-r--r-- 1 sbx_user1051  495    0 Sep 20 17:35 test
```

`touch /tmp/test` did work.

**Comment by mnapoli** [comment] 2019-09-20 17:37
Oh wait, maybe this is because the PHP-FPM worker is not running with the `sbx_user1051` user? (so the directory is writable, but that doesn't work in PHP itself)

Could it be because of this:

https://github.com/brefphp/bref/blob/7bfb18488e9fa91400de8f442419ef3748bc1ebb/runtime/layers/fpm-dev/php-fpm.conf#L13

**Comment by dhrrgn** [comment] 2019-09-20 17:37
The issue is that PHP-FPM is running as a different user, so it is not writable from a PHP process (sorry, I should have specified that).

```bash
bash-4.2$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
496          1  0.0  0.9 228500 19036 ?        Ss   17:21   0:00 php-fpm: master process (/opt/bref/etc/php-fpm.conf)
496          6  0.0  0.3 228500  6812 ?        S    17:21   0:00 php-fpm: pool default
496         36  1.3  0.1 115404  2820 pts/0    Ss   17:37   0:00 bash
496         42  0.0  0.1 117256  2396 pts/0    R+   17:37   0:00 ps aux
bash-4.2$
```

**Comment by mnapoli** [comment] 2019-09-20 17:41
I have changed the line to `user = sbx_user1051` and published the Docker images again, could you give it a try?

**Comment by dhrrgn** [comment] 2019-09-20 17:51
Still didn't work.  I did some digging, and I believe it may need to just be `sbx_user`, but I am not 100% sure on that.

**Comment by mnapoli** [comment] 2019-09-27 16:20
I added a (manual) test case here: https://github.com/brefphp/bref/pull/467/files#diff-de110db0af5c74274944e5824eecb0d6R33-R37 I confirm that things work correctly from what I've tried. Maybe that's just the latest fixes I've pushed to the docker image 🤔 

Anyway, if you can try again and let me know, maybe we can close this.

**Closed** 2019-11-09 17:40 UTC
Labels: bug
