### ISSUE TITLE
Basic setup encounters error 'couldn't find valid bootstrap'

### ISSUE THREAD

**Issue by jpike88** [brefphp/bref#536] opened 2020-01-22 06:57 UTC
This is all defaults, with a PHP Function type of project.

Attempting to run it gets this:

```serverless invoke local --docker -f function```

```{"errorType":"exitError","errorMessage":"RequestId: 26bc0da4-7311-16c9-7514-2ffe296837cf Error: Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap]"}```

**Comment by mnapoli** [comment] 2020-01-22 07:19
Thanks for the report, I think it's a duplicate of #409

**Closed by mnapoli** 2020-01-22 07:19 UTC
Labels: duplicate

**Comment by vk-sourcefuse** [comment] 2021-07-23 13:29
On my local, by clearing cache before invoking lambda worked fine, I'm using linux / ubuntu
```

docker system prune --all
sudo apt-get autoremove
sudo apt-get clean
sudo apt-get autoclean
sudo rm -rf ~/.cache/
sudo rm -rf /var/cache/
```
