### ISSUE TITLE
nyholm/psr7 has a symfony recipe that executes automatically

### ISSUE THREAD

**Issue by Nemo64** [brefphp/bref#619] opened 2020-04-13 12:11 UTC
I ran a composer update and symfony/flex automatically add [nyholm_psr7.yaml](https://github.com/symfony/recipes/blob/master/nyholm/psr7/1.0/config/packages/nyholm_psr7.yaml) to my symfony config folder because bref 0.5.21 has a dependency on [Nyholm/psr7](https://github.com/Nyholm/psr7).

I'm not against that dependency but i'm against it configuring itself into my project when I don't use it directly.

Can we do something about that?

**Comment by mnapoli** [comment] 2020-04-13 13:52
👍  @Nyholm is this automatic behavior intended? Is there a way to disable it?

**Comment by Nyholm** [comment] 2020-04-13 15:40
It is a flex recipe that adds that config. You can disable flex recipes if you want to. Like any recipes.

**Comment by mnapoli** [comment] 2020-04-13 16:13
👍 I see. In this situation, it's not really best that installing Bref in a Symfony project creates some unrelated config file in their projects (users don't really care that Bref has a PSR-7 implementation).

**Comment by Nyholm** [comment] 2020-04-13 17:09
I’m not sure. 

The config file adds some services. If services is not used they have no impact on performance. So there is no bad thing here. 

Also, this only happens if you are using flex in that project. Which is like saying: I want recipes. 

If you don’t want recipes but do want other features of flex you would install flex as a global dependency. 

@Nemo64 you can disable recipes in your project.

**Comment by Nemo64** [comment] 2020-04-13 17:57
Sure, but that would disable all recipes, even the ones I might want to execute.

Also: this isn't really about my projects. Every modern symfony project (which didn't change the flex default) will now have this file laying around which is pointless in most of them. This isn't really beautiful, is it?

**Comment by Nyholm** [comment] 2020-04-13 19:23
I think that is an issue you should open in the Symfony organization as it is not relevant to Bref nor nyholm/psr7

I also dont see the big issue, If you dont want the file you just remove it. And now you never need to care about it agian. =)

**Comment by mnapoli** [comment] 2020-04-14 07:57
> If you don't want the file you just remove it.

If it were only for the three of us, I would agree that it's not really a big deal. But this applies to all Bref users, for all level of experiences.

Installing Bref shouldn't install an unrelated file in their project (this is confusing and surprising).

**Comment by Nyholm** [comment] 2020-04-14 08:34
Hm, Im still not sure I understand the issue. 

1. It is a file that does nothing if you are not using it. It has zero performance impact.
2. It is common practise that Symfony Flex installs recipes for you.
3. It is **your** file, remove it if you don't like it. It will not constantly try to add the file each time you do a `composer update`
4. If you as an application developer thinks that "no files should be automatically added", then maybe Flex is not for you. Or if it is just this specific dependency you don't like, just make a PR to https://github.com/symfony/recipes and ask for its removal. 

If you feel that this is out of the ordinary (which it isnt), just remove the dependency and replace it with something else. But would you also remove `symfony/filesystem` or `symfony/process` or any other dependencies if there were a recipe for them?

**Comment by Nemo64** [comment] 2020-04-14 09:27
@Nyholm Nobody is talking about removing a dependency because of that.

The point of flex (to my understading) is: I install a new bundl/component/library and I get a template that shows me how to configure it. This is an awesome feature that I definitely wouldn't want to disable.

The problem comes when i install bref, i don't get a config file for bref. I get a config file for a psr7 library which i did not install. I installed bref. I now have a few ways to react to this:
- ignore it, in which case my project now has an implicit dependency to `Nyholm/psr7` and will break should this dependency not be required anymore
- remove that config file but for that I (hypothetical user that hasn't done the research yet) would have to figure out why it was even created, what it does and that I don't need it
- embrace it and properly create a hard dependency to `Nyholm/psr7` because my project now has a config file wich depends on that library being there.

And in all cases I increased the project complexity. Even when I remove that file: should I decide to 1 day use that library directly, I won't get the recipe because it was already installed so i'd have to know that.

All those issues would probably be solved when recipes of indirect dependencies wouldn't be executed automatically. I created an issue in flex for that: https://github.com/symfony/flex/issues/613

**Comment by deleugpn** [comment] 2021-09-19 14:36
Since this has been closed on the symfony side, perhaps we can close here, too?

**Comment by mnapoli** [comment] 2021-09-20 08:42
AFAIK the problem is still present, it has just been closed as "won't fix" on the Symfony side?

**Comment by SanderVerkuil** [comment] 2022-03-30 10:23
Apparently, Symfony flex will automatically clean up the files from a recipe if the dependency is no longer relevant, as can bee seen [here](https://github.com/symfony/flex/issues/613#issuecomment-613366648).

By installing this package, you already have an implicit dependency on [Nyholm/psr7](https://github.com/Nyholm/psr7), and if you remove the dependency on this package, the implicit dependency on [Nyholm/psr7](https://github.com/Nyholm/psr7) is also removed, and the changes made by the recipe should also be restored.

If that isn't the case, there most likely is a different bug in [Symfony/flex](https://github.com/symfony/flex).

**Comment by mnapoli** [comment] 2023-03-15 09:55
It's been two years now, let's close this.

**Closed by mnapoli** 2023-03-15 09:55 UTC
Labels: bug
