### ISSUE TITLE
download pdf or other issue "Failed encoding Lambda JSON response"

### ISSUE THREAD

**Issue by ashish-dirkmedia-de** [brefphp/bref#418] opened 2019-08-17 11:05 UTC
I have a lumen application which returns pdf or other data.
But I get "Failed encoding Lambda JSON response".

**Comment by AlessandroMinoccheri** [comment] 2019-08-20 20:45
Are you using API Gateway? Can you explain more how is structured your application to understand well the problem?

**Comment by ashish-dirkmedia-de** [comment] 2019-08-21 05:18
Yes Api gateway with "Use Lambda Proxy integration" and bref lambda with "php-72-fpm" layer. Using laravel

**Comment by mnapoli** [comment] 2019-08-21 07:24
This is a duplicate of #288 

This wasn't really obvious before, I have edited #288 to help people understand the problem a little bit better. Closing this issue.

**Closed by mnapoli** 2019-08-21 07:24 UTC
Labels: duplicate

**Comment by ashish-dirkmedia-de** [comment] 2019-11-06 16:12
Tried with the function validBase64($string)
still getting error
Using laravel with following code to download

$fileMimeType = Storage::disk('s3')->mimeType($fileLocation);
$headers = [
'Content-Type' => $fileMimeType,
'Content-Disposition' => 'attachment; filename="'.$fileName.'"'
];
Storage::disk('s3')->download($fileLocation, 200, $headers);

**Comment by ashish-dirkmedia-de** [comment] 2019-11-06 16:31
Even I tried
$contents = Storage::disk('s3')->get($fileLocation);

			return response(base64_encode($contents), 200)
				  ->header('Content-Type', $fileMimeType)
				  ->header('Content-Disposition', 'attachment; filename="'.$fileName.'"')
				  ->header('Cache-Control', 'public');
then the downloaded file is corrupted.
