### ISSUE TITLE
Deploy too big

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [brefphp/bref#361] opened 2019-06-28 12:43 UTC
Hi all, I have tried to deploy my simple http application written in symfony with only one controller and a route to have an endpoint to test this deployment system.
When I launcH

```
sam deploy \
    --template-file .stack.yaml \
    --capabilities CAPABILITY_IAM \
    --stack-name symfony-test
```

I have this error on cloudformation 

```

CREATE_FAILED

Unzipped  size must be smaller than 155681070 bytes (Service: AWSLambdaInternal;  Status Code: 400; Error Code: InvalidParameterValueException; Request  ID: 477adf87-99a1-11e9-a25d-cbc29f290f6a)

```

Before deploy I have launched:

```
composer install --optimize-autoloader --no-dev
```

Is it possible to solve this problem to deploy into a Lambda service?

Thanks

**Comment by mnapoli** [comment] 2019-06-28 12:45
Hi, I think this is a duplicate of #254, you should find a bit of help in that discussion.

Let us know if that doesn't help. (check any extra file that you don't need to deploy)

**Closed by mnapoli** 2019-06-28 12:45 UTC
Labels: duplicate
