### ISSUE TITLE
PHP lambda timing out

### ISSUE THREAD

**Issue by jmuraca** [brefphp/bref#873] opened 2021-02-28 16:10 UTC
Not sure if related to other time out tickets here so raising a new issue.

I'm running php-74-fpm on lambda and with a 25 second timeout, 2048 memory, and seeing a very consistent stream of timeouts at 25seconds. The bulk of the calls to my API are very quick (<1 second) and the function code is relatively tight/small. I've tried to trace it through the code or reduce database connections, but it seems to be getting close to an environment issue. 

![image](https://user-images.githubusercontent.com/1421873/109425100-839e1800-799b-11eb-89ef-1707cf3d16a7.png)

![image](https://user-images.githubusercontent.com/1421873/109425251-438b6500-799c-11eb-9f46-2d56e5260a7a.png)

Is there any way I can turn on additional logging or how can I help to provide more feedback?

**Comment by marcusirgens** [comment] 2021-02-28 16:18
Do you have any dependencies downstream that might be timing out?

**Comment by jmuraca** [comment] 2021-02-28 16:32
I have an RDS database connected and Cloudwatch logging.  I reduced database calls and the database seems to have extra capacity. 

I can't replicate time outs on the staging or local environments. I'm not sure if that's a good or bad thing though. It could be that having many more requests on product is causing something else to timeout or be blocked, but I'm also trying to isolate if having more invocations of bref means the issue happens more frequently.

**Comment by jmuraca** [comment] 2021-02-28 17:07
Is there a way I could correlate a run of the bref instance with the application runtime instance? That way I could step through application logs to see if it actually ends or hangs at a point, compared to the bref instance timing out.

**Comment by matthewsuan** [comment] 2021-02-28 17:16
Try to enable xray tracing on your lambda function. I usually do it via:

```
provider:
  tracing:
    lambda: true
```

In Xray, you can see the entire invocation lifecycle and the cause the of timeout.

**Comment by mnapoli** [comment] 2021-02-28 18:10
Could it be that you have a piece of code that calls an API that times out?

Usually that's something like Sentry/bugsnag (which would timeout when there's an error to report). Related: does your VPC has a NAT Gateway?

**Comment by jmuraca** [comment] 2021-03-01 22:13
Turned on Xray for the past day. I didn't find it particularly useful since I'm building with Bref, single API Gateway function, into a single PHP instance with a Router internal. I haven't looked if/how this should be broken up yet as was hoping to move this to Lambda from EC2's
![image](https://user-images.githubusercontent.com/1421873/109565664-a57cc500-7a97-11eb-86f0-0bcdbd7e8dc9.png)

I am not using Sentry or other applications currently. I'm running AWS SSM parameters for config (at runtime, cached locally, not timing out), RDS for a database and Cloudwatch for logs.

I simplified the the main endpoint queried by clients for traffic, and all it has now is 
1. request SSM Parameters (SSM or cache if exists)
2. Read query params, load appropriate RDS functions
3. Return JSON output
Along the way, Cloudwatch logs as needed.

**Comment by jmuraca** [comment] 2021-03-01 22:14
From Xray and Cloudwatch logs, I don't see errors and lots of 200 HTTP status codes
![Uploading image.png…]()

**Comment by jmuraca** [comment] 2021-03-02 01:19
I've been playing around with additional logs all day. Most functions run in <400ms with the p99 max for duration around 4 to 5 second. I set a timeout to 8 seconds, previously 25 seconds. While I still get timeouts, the error in the logs is now more descriptive per some other tickets I've seen here.

Not sure if my 25 second vs 8 second time out are related, but the number of occurrences hasn't gone up so I suspect there are the same for now.

![image](https://user-images.githubusercontent.com/1421873/109581924-0d400980-7ab2-11eb-8449-987fea9360c7.png)
![image](https://user-images.githubusercontent.com/1421873/109582005-3365a980-7ab2-11eb-9c8b-6dfa2ab0480e.png)

**Comment by jmuraca** [comment] 2021-03-04 19:04
After some digging and eliminating one culprit is Cloudwatch logs.  I am using Monolog (Maxbanton\Cwh\Handler\CloudWatch) and paused logs for the most frequently called endpoint and this has dropped timeouts to zero.

![image](https://user-images.githubusercontent.com/1421873/110012888-df3b0f00-7cd5-11eb-882f-8447e3d936e7.png)

Any ideas why this could be?

I've seen the Bref logging repo but it doesn't appear to support multiple streams and just logs direct to output. Maybe that in itself is my architecture issue - I want to log to streams to separate my logs when they were in a more monolithic API, but need to consider splitting this up to different functions sooner than expected.

**Comment by mnapoli** [comment] 2021-03-05 14:08
That CloudWatch library seems to do some waiting in case you have many logs to send:

https://github.com/maxbanton/cwh/blob/d18f16d2df2456ecdd061b5414d55a8a9736b23d/src/Handler/CloudWatch.php#L202-L218

Additionally, it sends log via HTTP. A common mistake is not configuring connection timeouts. If that library tries to call Cloudwatch and either:

- waits for 10 or even 30s because of a network fluke
- or waits in a loop (with `sleep`) to avoid spamming the cloudwatch API

then that could explain your Lambda timeouts.

Is there any reason you are not following the Bref default recommendation of logging to stderr?

**Comment by jmuraca** [comment] 2021-03-05 23:18
I have essentially "lifted and shifted" my application into lambda with the aim to start breaking it apart as we scale. This was the start of that process. I will be reviewing and updating the logging library to the bref one with priority in the coming days. Thanks for the suggestion and awesome project! I'll aim to have my team contribute where possible as we develop.
I'll report back here with the outcome to hopefully have saved future people some time.

**Comment by peldax** [comment] 2021-03-08 14:16
I can confirm this issue. I get exactly three requests per minute, which timeout at 10 seconds.

I would also like to take this opportunity to thank for this amazing project. It made deploying to AWS really easy, even with usage of non-standard PHP extensions.

**Comment by mnapoli** [comment] 2021-03-08 15:21
It's hard to be 100% sure for everyone's issue, but 95% of all "Timeout" issues I've seen are:

- your app is deployed in a VPC (because you use RDS) and by default VPC cuts internet access for Lambda (see https://bref.sh/docs/environment/database.html#accessing-the-internet)
- your app calls APIs that answer in more than 30 seconds (for example they're really slow, or they're down), and your code is not configured to time out before 30 seconds (so the Lambda ends up timing out, which is a more cryptic error)

My generic advice: read about VPC + setup shorter timeouts in all of your HTTP clients and libraries (in your code).

Hope that helps!

**Comment by peldax** [comment] 2021-03-08 16:16
Yes, I understand that its most likely issue on our end.

We indeed connect to our RDS, but at the moment we were using only introspection queries, which should not touch database at all. I am currently investigating further.

**Comment by peldax** [comment] 2021-03-08 18:21
Hello, as you suspected, I found the issue on our end.

My colleague had graphqli opened in background, and it periodically tried to refresh failing queries - and those queries timed out timed out.

**Comment by mnapoli** [comment] 2021-03-08 21:20
👍  your comment actually prompted me to update the documentation a bit to help users debug these timeouts a bit sooner: https://bref.sh/docs/environment/database.html#accessing-the-internet

**Comment by mnapoli** [comment] 2021-09-18 09:08
> Hello, as you suspected, I found the issue on our end.
>
> My colleague had graphqli opened in background, and it periodically tried to refresh failing queries - and those queries timed out.

Closing the issue since it was resolved.

**Closed by mnapoli** 2021-09-18 09:08 UTC
Labels: bug
