### ISSUE TITLE
Brefv2: application not getting refreshed in local development setup

### ISSUE THREAD

**Issue by JakubPat** [brefphp/bref#1570] opened 2023-06-16 12:07 UTC
**Description:**
Hi, we recently switched for bref 2 running on symfony. The way that we used to develop locally while on bref v1 on every change of the code, application refreshed within deployed docker container. But currently even after clearing cache no change gets applied until tearing down container.

Below it's our docker config:
`FROM bref/php-80-fpm-dev:2
COPY --from=bref/extra-gd-php-80:1 /opt /opt
`
```
version: "3.5"

services:
  php:
    ports:
      - '8000:8000'
    build:
        context: .
        dockerfile: docker/Dockerfile-phpFpm
    volumes:
      - .:/var/task:ro
    environment:
      BREF_BINARY_RESPONSES: '1'
      HANDLER: public/index.php
    networks:
      - local-network
```

**How to reproduce:**

**Comment by mnapoli** [comment] 2023-06-16 12:14
Hi, I don't see an obvious reason why that would happen.

I'd suggest investigating if there's anything exotic in your config, or maybe creating the smallest reproducible example possible?

**Comment by mnapoli** [comment] 2024-03-19 14:53
Closing because it cannot be reproduced.

**Closed by mnapoli** 2024-03-19 14:53 UTC
Labels: bug
